name: Build and Publish  
  
on:  
  push:  
    branches: [ master ]   
    tags:  
       - 'v*' # 触发条件为push带有v前缀的标签
  
jobs:  
  build:  
    runs-on: windows-latest  
  
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v3  
  
    - name: Setup .NET 8  
      uses: actions/setup-dotnet@v3  
      with:  
        dotnet-version: '8.x'  
  
    - name: Restore dependencies  
      run: dotnet restore CymaticLabs.InfluxDB.sln  
  
    - name: Build application
      run: dotnet build CymaticLabs.InfluxDB.sln --configuration Release --no-restore  
  
    - name: Publish  
      run: dotnet publish src/CymaticLabs.InfluxDB.Studio/CymaticLabs.InfluxDB.Studio.csproj --configuration Release --output ./publish_output /p:PublishSingleFile=true 
  
    - name: Zip Release Artifacts  
      run: Compress-Archive -Path ./publish_output/* -DestinationPath ./InfluxDBStudio.zip  
      shell: pwsh  

    - name: Get Version Info  
      id: get_version_info  
      run: 
        # 使用 Git 命令获取最新 tag
        git fetch --tags
        $latest_tag = git describe --tags --abbrev=0
        echo "Latest tag:$latest_tag"
        echo "::set-output name=tag_name::$latest_tag"
        $version=${latest_tag#v}
        echo "::set-output name=version::$version"
      shell: pwsh  
  
  
    - name: Get Commit Info  
      id: get_commit_info  
      run: |  
        # 获取最近一次commit的信息，你可以根据需要调整这个命令  
        $commitInfo = git log -1 --pretty=format:"%s"  
        echo "::set-output name=commit_message::$commitInfo"  
      shell: pwsh  
  
    - name: Create Release  
      id: create_release  
      uses: ncipollo/release-action@v1  
      with:  
        token: ${{ secrets.GITHUB_TOKEN }}  
        artifacts: "./InfluxDBStudio.zip"  
        tag: ${{ steps.get_version_info.outputs.version }}  
        name: Release ${{ steps.get_version_info.outputs.version }}  
        body: |  
          Release version: ${{ steps.get_version_info.outputs.version }}  
          This release includes the following changes:  
          - ${{ steps.get_commit_info.outputs.commit_message }}  
        draft: false  
        prerelease: false
