name: Build and Publish  
  
on:  
  workflow_dispatch:
    inputs:
      version_name:
        description: 'pls input tag name'
        required: true
  
jobs:  
  build:  
    if: github.actor == github.repository_owner
    runs-on: windows-latest  
  
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v3  
      with:
        fetch-depth: 0 # 获取完整的 Git 历史记录
  
    - name: Setup .NET 8  
      uses: actions/setup-dotnet@v3  
      with:  
        dotnet-version: '8.x'  
  
    - name: Restore dependencies  
      run: dotnet restore CymaticLabs.InfluxDB.sln  
  
    - name: Build application
      run: dotnet build CymaticLabs.InfluxDB.sln --configuration Release --no-restore  
  
    - name: Publish  
      run: dotnet publish src/CymaticLabs.InfluxDB.Studio/CymaticLabs.InfluxDB.Studio.csproj --configuration Release --output ./publish_output /p:PublishSingleFile=true 
  
    - name: Zip Release Artifacts  
      run: Compress-Archive -Path ./publish_output/* -DestinationPath ./InfluxDBStudio.zip  
      shell: pwsh  

    - name: Fetch Tag  
      id: git_fetch_tag  
      run: git fetch --tags
 
    - name: Get Commit Info  
      id: get_commit_info  
      run: |  
        # 获取最近一次commit的信息，你可以根据需要调整这个命令  
        $commitInfo = git log -1 --pretty=format:"%s"  
        echo "::set-output name=commit_message::$commitInfo"  
      shell: pwsh  
  
    - name: Create Release  
      id: create_release  
      uses: ncipollo/release-action@v1  
      with:  
        token: ${{ secrets.GITHUB_TOKEN }}  
        artifacts: "./InfluxDBStudio.zip"  
        tag: ${{ github.event.inputs.version_name }}  
        name: Release ${{github.event.inputs.version_name }}  
        body: |  
          Release version: ${{github.event.inputs.version_name }}  
          This release includes the following changes:  
          - ${{ steps.get_commit_info.outputs.commit_message }}  
        draft: false  
        prerelease: false
