name: Build and Publish  
  
on:  
  push:  
    branches: [ master ]   
    tags:  
       - 'v*' # 触发条件为push带有v前缀的标签
  
jobs:  
  build:  
    runs-on: windows-latest  
  
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v3  
  
    - name: Setup .NET 8  
      uses: actions/setup-dotnet@v3  
      with:  
        dotnet-version: '8.x'  
  
    - name: Restore dependencies  
      run: dotnet restore CymaticLabs.InfluxDB.sln  
  
    - name: Build application
      run: dotnet build CymaticLabs.InfluxDB.sln --configuration Release --no-restore  
  
    - name: Publish  
      run: dotnet publish src/CymaticLabs.InfluxDB.Studio/CymaticLabs.InfluxDB.Studio.csproj --configuration Release --output ./publish_output /p:PublishSingleFile=true 
  
    - name: Zip Release Artifacts  
      run: Compress-Archive -Path ./publish_output/* -DestinationPath ./InfluxDBStudio.zip  
      shell: pwsh  

    - name: Get Version Info  
      id: get_version_info  
      run: 
        git fetch --tags
        $TAG_NAME=$(git describe --tags)
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        echo ::set-output name=version_name::$TAG_NAME
      # 从标签中提取版本号，假设标签格式为v1.2.3  
      shell: pwsh  
  
  
    - name: Get Commit Info  
      id: get_commit_info  
      run: |  
        # 获取最近一次commit的信息，你可以根据需要调整这个命令  
        $commitInfo = git log -1 --pretty=format:"%s"  
        echo "::set-output name=commit_message::$commitInfo"  
      shell: pwsh  
  
    - name: Create Release  
      id: create_release  
      uses: ncipollo/release-action@v1  
      with:  
        token: ${{ secrets.GITHUB_TOKEN }}  
        artifacts: "./InfluxDBStudio.zip"  
        tag: ${{ steps.get_version_info.outputs.version_name }}  
        name: Release ${{ steps.get_version_info.outputs.version_name }}  
        body: |  
          Release version: ${{ steps.get_version_info.outputs.version_name }}  
          This release includes the following changes:  
          - ${{ steps.get_commit_info.outputs.commit_message }}  
        draft: false  
        prerelease: false
